/**
 * File: AbstractPostEntry.java
 * Date: 11/9/12 3:10 PM
 * Version: 1.0
 * 
 * This file was autogenerated by contract.io.  Any changes will be overwritten if code generation is
 * invoked on this file.  In addition, other modules may have dependencies on definitions in this file.
 * 
 * EDIT AT YOUR OWN RISK!
 */

package com.eo.publish;

import com.eo.publish.Author;
import com.eo.publish.AbstractPost;
import java.io.IOException;
import java.io.DataInputStream;
import java.io.DataOutputStream;


public class AbstractPostEntry {
	protected Long postId;
	protected Author author;
	protected Long datePublished;
	protected AbstractPost post;

	public void setPostId(Long postId) {
		this.postId = postId;
	}
	public Long getPostId() {
		return postId;
	}
	public void setAuthor(Author author) {
		this.author = author;
	}
	public Author getAuthor() {
		return author;
	}
	public void setDatePublished(Long datePublished) {
		this.datePublished = datePublished;
	}
	public Long getDatePublished() {
		return datePublished;
	}
	public void setPost(AbstractPost post) {
		this.post = post;
	}
	public AbstractPost getPost() {
		return post;
	}
	public void encodeContract(DataOutputStream out) throws IOException {
		out.writeLong(postId);
		out.writeLong(datePublished);
	}

	public void decodeContract(DataInputStream in) throws IOException, ClassNotFoundException {
		postId = in.readLong();
		datePublished = in.readLong();
	}

}
