/**
 * File: Author.java
 * Date: 11/9/12 3:10 PM
 * Version: 1.0
 * 
 * This file was autogenerated by contract.io.  Any changes will be overwritten if code generation is
 * invoked on this file.  In addition, other modules may have dependencies on definitions in this file.
 * 
 * EDIT AT YOUR OWN RISK!
 */

package com.eo.publish;

import java.io.IOException;
import java.io.DataInputStream;
import java.io.DataOutputStream;


public class Author {
	protected Long postId;
	protected String name;
	protected String authorId;
	protected String sor;

	public void setPostId(Long postId) {
		this.postId = postId;
	}
	public Long getPostId() {
		return postId;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getName() {
		return name;
	}
	public void setAuthorId(String authorId) {
		this.authorId = authorId;
	}
	public String getAuthorId() {
		return authorId;
	}
	public void setSor(String sor) {
		this.sor = sor;
	}
	public String getSor() {
		return sor;
	}
	public void encodeContract(DataOutputStream out) throws IOException {
		out.writeLong(postId);
		out.writeUTF(name);
		out.writeUTF(authorId);
		out.writeUTF(sor);
	}

	public void decodeContract(DataInputStream in) throws IOException, ClassNotFoundException {
		postId = in.readLong();
		name = in.readUTF();
		authorId = in.readUTF();
		sor = in.readUTF();
	}

}
