/**
 * File: Comment.java
 * Date: 11/9/12 3:10 PM
 * Version: 1.0
 * 
 * This file was autogenerated by contract.io.  Any changes will be overwritten if code generation is
 * invoked on this file.  In addition, other modules may have dependencies on definitions in this file.
 * 
 * EDIT AT YOUR OWN RISK!
 */

package com.eo.publish;

import com.eo.publish.AbstractPost;
import java.io.IOException;
import java.io.DataInputStream;
import java.io.DataOutputStream;


public class Comment extends AbstractPost {
	protected String text;
	protected String url;

	public void setText(String text) {
		this.text = text;
	}
	public String getText() {
		return text;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getUrl() {
		return url;
	}
	public void encodeContract(DataOutputStream out) throws IOException {
		super.encodeContract(out);
		out.writeUTF(text);
		out.writeUTF(url);
	}

	public void decodeContract(DataInputStream in) throws IOException, ClassNotFoundException {
		super.decodeContract(in);
		text = in.readUTF();
		url = in.readUTF();
	}

}
