/**
 * File: CreatePostRequest.java
 * Date: 11/9/12 3:10 PM
 * Version: 1.0
 * 
 * This file was autogenerated by contract.io.  Any changes will be overwritten if code generation is
 * invoked on this file.  In addition, other modules may have dependencies on definitions in this file.
 * 
 * EDIT AT YOUR OWN RISK!
 */

package com.eo.publish;

import com.eo.publish.AbstractPost;
import com.eo.message.AbstractRequest;
import java.io.IOException;
import java.io.DataInputStream;
import java.io.DataOutputStream;


public class CreatePostRequest extends AbstractRequest {
	protected AbstractPost post;

	public void setPost(AbstractPost post) {
		this.post = post;
	}
	public AbstractPost getPost() {
		return post;
	}
	public void encodeContract(DataOutputStream out) throws IOException {
		super.encodeContract(out);
	}

	public void decodeContract(DataInputStream in) throws IOException, ClassNotFoundException {
		super.decodeContract(in);
	}

}
