/**
 * File: InvalidArguments.java
 * Date: 11/9/12 3:10 PM
 * Version: 1.0
 * 
 * This file was autogenerated by contract.io.  Any changes will be overwritten if code generation is
 * invoked on this file.  In addition, other modules may have dependencies on definitions in this file.
 * 
 * EDIT AT YOUR OWN RISK!
 */

package com.eo.publish;

import java.io.IOException;
import java.io.DataInputStream;
import java.io.DataOutputStream;


public class InvalidArguments extends Exception {

	public void encodeContract(DataOutputStream out) throws IOException {
	}

	public void decodeContract(DataInputStream in) throws IOException, ClassNotFoundException {
	}
}
