/**
 * File: Publish.java
 * Date: 11/9/12 3:10 PM
 * Version: 1.0
 * 
 * This file was autogenerated by contract.io.  Any changes will be overwritten if code generation is
 * invoked on this file.  In addition, other modules may have dependencies on definitions in this file.
 * 
 * EDIT AT YOUR OWN RISK!
 */

package com.eo.publish;

import com.eo.publish.UpdatePostResponse;
import com.eo.publish.UpdatePostRequest;
import com.eo.publish.CreatePostResponse;
import com.eo.publish.DeletePostsResponse;
import com.eo.publish.DeletePostRequest;
import com.eo.publish.InvalidArguments;
import com.eo.publish.InvalidCredentials;
import com.eo.publish.ServerError;
import com.eo.publish.CreatePostRequest;
import com.eo.publish.RetrievePostsResponse;
import com.eo.publish.RetrievePostsRequest;


public interface Publish {

	public CreatePostResponse create(CreatePostRequest post) throws InvalidCredentials, InvalidArguments, ServerError;
	public RetrievePostsResponse retrieve(RetrievePostsRequest query) throws InvalidCredentials, InvalidArguments, ServerError;
	public UpdatePostResponse update(UpdatePostRequest post) throws InvalidCredentials, InvalidArguments, ServerError;
	public DeletePostsResponse delete(DeletePostRequest query) throws InvalidCredentials, InvalidArguments, ServerError;
}
