/**
 * File: RetrievePostsResponse.java
 * Date: 11/9/12 3:10 PM
 * Version: 1.0
 * 
 * This file was autogenerated by contract.io.  Any changes will be overwritten if code generation is
 * invoked on this file.  In addition, other modules may have dependencies on definitions in this file.
 * 
 * EDIT AT YOUR OWN RISK!
 */

package com.eo.publish;

import java.util.LinkedList;
import java.util.List;
import com.eo.publish.AbstractPostEntry;
import com.eo.message.AbstractResponse;
import java.io.IOException;
import java.io.DataInputStream;
import java.io.DataOutputStream;


public class RetrievePostsResponse extends AbstractResponse {
	protected List<AbstractPostEntry> postEntries;

	public void setPostEntries(List<AbstractPostEntry> postEntries) {
		this.postEntries = postEntries;
	}
	public List<AbstractPostEntry> getPostEntries() {
		return postEntries;
	}
	public void encodeContract(DataOutputStream out) throws IOException {
		super.encodeContract(out);
		out.writeInt(postEntries.size());
		for (AbstractPostEntry element : postEntries) {
			element.encodeContract(out);
		}
	}

	public void decodeContract(DataInputStream in) throws IOException, ClassNotFoundException {
		super.decodeContract(in);
		postEntries = new LinkedList<AbstractPostEntry>();
		int count = in.readInt();
		for (int i = 0; i < count; i++) {
			AbstractPostEntry element = new AbstractPostEntry();
			element.decodeContract(in);
			postEntries.add(element);
		}
	}

}
