/**
 * File: UpdatePostRequest.java
 * Date: 11/9/12 3:10 PM
 * Version: 1.0
 * 
 * This file was autogenerated by contract.io.  Any changes will be overwritten if code generation is
 * invoked on this file.  In addition, other modules may have dependencies on definitions in this file.
 * 
 * EDIT AT YOUR OWN RISK!
 */

package com.eo.publish;

import com.eo.publish.AbstractPost;
import java.util.HashSet;
import java.util.Set;
import com.eo.message.AbstractRequest;
import java.io.IOException;
import java.io.DataInputStream;
import java.io.DataOutputStream;


public class UpdatePostRequest extends AbstractRequest {
	protected Set<Long> sors;
	protected Long postId;
	protected AbstractPost post;

	public void setSors(Set<Long> sors) {
		this.sors = sors;
	}
	public Set<Long> getSors() {
		return sors;
	}
	public void setPostId(Long postId) {
		this.postId = postId;
	}
	public Long getPostId() {
		return postId;
	}
	public void setPost(AbstractPost post) {
		this.post = post;
	}
	public AbstractPost getPost() {
		return post;
	}
	public void encodeContract(DataOutputStream out) throws IOException {
		super.encodeContract(out);
		out.writeInt(sors.size());
		for (Long element : sors) {
			out.writeLong(element);
		}
		out.writeLong(postId);
	}

	public void decodeContract(DataInputStream in) throws IOException, ClassNotFoundException {
		super.decodeContract(in);
		sors = new HashSet<Long>();
		int count = in.readInt();
		for (int i = 0; i < count; i++) {
			Long element;
			element = in.readLong();
			sors.add(element);
		}
		postId = in.readLong();
	}

}
