/**
 * File: AbstractRequest.java
 * Date: 11/9/12 3:10 PM
 * Version: 1.0
 * 
 * This file was autogenerated by contract.io.  Any changes will be overwritten if code generation is
 * invoked on this file.  In addition, other modules may have dependencies on definitions in this file.
 * 
 * EDIT AT YOUR OWN RISK!
 */

package com.eo.message;

import java.io.IOException;
import java.io.DataInputStream;
import java.io.DataOutputStream;


public class AbstractRequest {
	protected Integer messageId;
	protected String userName;
	protected String password;
	protected Long lastUpdate;

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}
	public Integer getMessageId() {
		return messageId;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getUserName() {
		return userName;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getPassword() {
		return password;
	}
	public void setLastUpdate(Long lastUpdate) {
		this.lastUpdate = lastUpdate;
	}
	public Long getLastUpdate() {
		return lastUpdate;
	}
	public void encodeContract(DataOutputStream out) throws IOException {
		out.writeInt(messageId);
		out.writeUTF(userName);
		out.writeUTF(password);
		out.writeLong(lastUpdate);
	}

	public void decodeContract(DataInputStream in) throws IOException, ClassNotFoundException {
		messageId = in.readInt();
		userName = in.readUTF();
		password = in.readUTF();
		lastUpdate = in.readLong();
	}

}
