/**
 * File: StatusCode.java
 * Date: 11/9/12 3:10 PM
 * Version: 1.0
 * 
 * This file was autogenerated by contract.io.  Any changes will be overwritten if code generation is
 * invoked on this file.  In addition, other modules may have dependencies on definitions in this file.
 * 
 * EDIT AT YOUR OWN RISK!
 */

package com.eo.message;



public enum StatusCode {
	OK, EntryNotFound, IllegalMessageFormat, ServerError, InvalidCredentials}
